### ISSUE TITLE
Feature Additions/Enhancements

### ISSUE THREAD

**Issue by rishabhp** [rishabhp/bideo.js#1]
- [x] Responsive web (mobile) support.
- [x] Support for play/pause buttons (for iOS, etc.).
- [x] Support for Youtube iframe embeds. (Swapping `video` with YouTube's `iframe` tag should be good enough. [List of options](https://developers.google.com/youtube/player_parameters).)

**Comment by bgold0** [comment]
+1 for mobile support

**Comment by air720boarder** [comment]
+1 for mobile and Youtube

**Comment by stelboe** [comment]
+1 for mobile support

**Comment by rishabhp** [comment]
Almost done except with some quirks which will be taken up in #8

**Comment by lmartins** [comment]
Would love support for YouTube and mobile too.
