### ISSUE TITLE
playing video with random pause interval and reverse playback

### ISSUE THREAD

**Issue by dimitrieh** [rishabhp/bideo.js#11]
Hiya, thanks for this awesome plugin! 💯 

I was wondering. Say you have a video of approximately 2 seconds. You want to wait before playing it, lets say 5 seconds. then play it, wait at last frame for 3 seconds, play it in reverse, then wait again a few seconds. Random intervals would be a bonus.

How would i go about that? :)

**Comment by rishabhp** [comment]
1. Wait (of say 5s) can be achieved with a `setTimeout` inside `loadedmetadata` or `canplay` events.

2. Then play it and wait for 3s in the `ended` event.

3. Finally if you want to play it in reverse then I haven't tried that, but try this [solution](http://stackoverflow.com/a/22777473/2272910).

It'll all require custom logic so integrating that into the plugin doesn't seem essential.
