### ISSUE TITLE
doesn't appear to be working at all

### ISSUE THREAD

**Issue by selfagency** [rishabhp/bideo.js#19]
using this code—

```
import 'rishabhp/bideo.js'

export function videoHeader () {
  const bgvid = new Bideo()
  bgvid.init({
    videoEl: document.querySelector('#bgvid'),
    container: document.querySelector('#custom-header'),
    resize: true,
    autoplay: true,
    isMobile: window.matchMedia('(max-width: 768px)').matches,
    src: [
      {
        src: '/video/video_header.mp4',
        type: 'video/mp4'
      }
    ]
  })
}
```
and this css
```
#custom-header {
  height: 100vh;
  width: 100vw;
}
```
—the only thing that happens is a source element gets inserted into the video element. the video doesn't load. it doesn't stretch the video element to fit the container. no new styles are applied to the video element or container. if i put the src directly in the video tag, the video loads but doesn't stretch to fit the container.

**Comment by glaucomorais** [comment]
If you are using Chrome to develop, you must be warned that the CSS code for the video tag must have an `object-fit` property. If this property is not present nothing will be accomplished.

See the line [122](https://github.com/rishabhp/bideo.js/blob/91582dd6961cb4d621d4774506e6c447128206ac/bideo.js#L124) from the source code.

Sample CSS that will probably work:
```
#background-video {
      object-fit: cover;
      position: absolute;
      transform: translate(-50%, -50%);

      width: 100%;
      height: 100%;

      top: 50%;
      left: 50%;
    }
```

**Comment by selfagency** [comment]
ty
