### ISSUE TITLE
This can be solved with CSS.

### ISSUE THREAD

**Issue by birkir** [rishabhp/bideo.js#7]
http://codepen.io/birkir/pen/EyxOYz

IE doesn't know how to object-fit, but theres an polyfill [1] which is certainly smaller and moe universal than this plugin. Other browsers support it well [2].

[1] https://github.com/jonathantneal/fitie
[2] http://caniuse.com/#search=object-fit

**Comment by rishabhp** [comment]
I agree with the `object-fit` solution. There are certain polyfills but the one you've linked won't work on Edge. I'll update the article as well as the code with necessary info soon.
